---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
     update_cache: yes

  - name: install apache2 against the two nodes
    apt:
      name: apache2  
      state: absent

  - name: install php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
