---

- hosts: all
  become: true
  pre_tasks:
  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site 
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install unzip
    package:
      name: unzip
  
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      group: root
      owner: root
      mode: 0755

- hosts: web_servers
  become: true
  tasks:
  - name: install apache2 and php in the two nodes ubuntu
    apt:
      name:
       - apache2
       - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "ubuntu" 
